title: "Mohammed Abdul Hafeez Khan"
description: "PhD student • NASA RA • Research in generative AI, distribution shift, and medical AI"
url: "https://www.ma-hafeez-khan.com"
baseurl: ""
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-scholar

scholar:
  style: ieee
  locale: en
  source: _bibliography
  bibliography: papers.bib
  sort_by: year,month
  order: descending
  # Use a minimal custom template (see _layouts/bib.html)
  bibliography_template: bib

# Navigation
nav:
  - name: "About"
    link: "/"
  - name: "Publications"
    link: "/publications/"
  - name: "CV"
    link: "/cv/"
